### ISSUE TITLE
Готовност за разработка

### ISSUE THREAD

**Issue by thesunlover** [otvorete/petition#11]
Предлагам да се добави към петицията следното пояснение, макар и очевидно за нас разработчиците: Можете да видите, колко от нас с готовност биха се включили в разработката и подобрението на софтуера [тук](https://github.com/otvorete/petition/watchers)

**Comment by kspirov** [comment]
Ако се бяхме сетили в началото, може би щеше да е добра идея, но в момента
Watchers се използва по класическия начин, няма нужда да го абюзваме. Хората са си се закачили като watchers, за да гледат как се променя текста (точно каквато е идеята на тази опция), така че примерно ако петицията бъде радикално променена, да могат да оттеглят подписа си. Тази опция е много добра и  полезна за колегите, не би трябвало да я отнемаме за друго. Освен това нали знаеш комитмънта на програмистите... Мисля, че "мнозина от нас са готови" е достатъчен, доброволчеството винаги се прави при "благовремие", но и това е fair deal.
