### ISSUE TITLE
Не можа да се ъплудват файлове.

### ISSUE THREAD

**Issue by vasence** [otvorete/petition#12]
Като начало "Катедралата и базарът"  https://chitanka.info/text/32547-katedralata-i-bazaryt.txt.zip 
Към допълнителните файлове освен readme.md

**Comment by lunohodov** [comment]
Ъплудват. Защо чуждица?

Какво мислиш за "прикачват"?

**Comment by kspirov** [comment]
Нека нещата са фокусирани около петицията, карай
