### ISSUE TITLE
Думата "приказва" е твърде разговорна

### ISSUE THREAD

**Issue by teoparvanov** [otvorete/petition#3]
Според мен, трябва да заменим глагола "приказва" с "говори".

Поздрави,
Тео

**Comment by kspirov** [comment]
Това със сигурност е по-автентичният превод на Линус. Според мен основателния ти concern е, че така изглежда по-несериозно, може и така да е. Аз първоначално го бях превел като "приказките са евтини", но взех мнения тук и там и стигнах до това. Дай да не пипаме, че това е промяна отвъд очевидните редакционни.

**Comment by teoparvanov** [comment]
Просто не ми се иска да станем за смях, ако тази петиция се озове в медиите след някой друг ден.
Но пък от друга страна, "приказва" внася и малко колорит :).
