### ISSUE TITLE
Счупен линк

### ISSUE THREAD

**Issue by teoparvanov** [otvorete/petition#4]
Също така, линк [5] (за Естония) изглежда не работи:

http://www.h-online.com/open/news/item/Estonian-Government-publishes-open-source-policy-1097623.html%3Ffbclid=IwAR3EZM2m4pPvbpFfY4L_1kL4OwceiSmACDDwZV9-0iUUG8ZOrdWH5yMu7dA

**Comment by kspirov** [comment]
Fixed in commit f555824ef4bce208320d56651518a9b6ea67f5a1
