### ISSUE TITLE
Да прибавим ли след петицията "справка" за закона за електронното управление

### ISSUE THREAD

**Issue by kspirov** [otvorete/petition#5]
Петицията вече е пусната.

Да не пипаме, или да прибавим ли в края (под нея) нещо като:

Справка, според закона за Електронното Управление чл. 58а, ал. 1, точка а) компютърните програми трябва да отговарят на критериите за софтуер с отворен код;
 https://www.lex.bg/laws/ldoc/2135555445

Настоящата петиция  призовава не само към спазването на закона, но и неща писани преди приемането на тази поправка да станат публични.

**Comment by ShaManHFel** [comment]
На мен ми е интересно да знам за нещата писани от приемането на на тази поправка насам къде им е кода.

**Comment by teoparvanov** [comment]
+1 за справката!

**Comment by elfoles** [comment]
+1 за справката!

**Comment by kspirov** [comment]
СПРАВКА: според закона за Електронното Управление чл. 58а, ал. 1, точка а) компютърните програми трябва да отговарят на критериите за софтуер с отворен код (https://www.lex.bg/laws/ldoc/2135555445)

Настоящата петиция призовава не само към спазването на закона, но и към разширяване на обхвата му.

**Comment by kspirov** [comment]
+1 и от мен

**Comment by kspirov** [comment]
СПРАВКА: според закона за Електронното Управление чл. 58а, ал. 1, точка а) компютърните програми трябва да отговарят на критериите за софтуер с отворен код (https://www.lex.bg/laws/ldoc/2135555445)

Настоящата петиция призовава не само към спазването на закона, но и към разширяване на обхвата му.

**Comment by todorspasov** [comment]
+1
